# TCL File Generated by Component Editor 18.1
# Sat Nov 19 16:57:09 CET 2022
# DO NOT MODIFY


# 
# uart_basic "UART_basic" v1.0
# GHOST 2022.11.19.16:57:09
# a basic UART for FYS4220
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module uart_basic
# 
set_module_property DESCRIPTION "a basic UART for FYS4220"
set_module_property NAME uart_basic
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP FYS4220
set_module_property AUTHOR GHOST
set_module_property DISPLAY_NAME UART_basic
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL uart
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file uart.vhd VHDL PATH ../../GitHub/FYS4220-project/project/src/uart.vhd TOP_LEVEL_FILE
add_fileset_file UART_tx.vhd VHDL PATH ../../GitHub/FYS4220-project/project/src/UART_tx.vhd
add_fileset_file UART_rx.vhd VHDL PATH ../../GitHub/FYS4220-project/project/src/UART_rx.vhd
add_fileset_file baudrategen.vhd VHDL PATH ../../GitHub/FYS4220-project/project/src/baudrategen.vhd
add_fileset_file baudrategen_rx.vhd VHDL PATH ../../GitHub/FYS4220-project/project/src/baudrategen_rx.vhd
add_fileset_file bitcounter.vhd VHDL PATH ../../GitHub/FYS4220-project/project/src/bitcounter.vhd
add_fileset_file bitcounter_rx.vhd VHDL PATH ../../GitHub/FYS4220-project/project/src/bitcounter_rx.vhd
add_fileset_file tx_fsm.vhd VHDL PATH ../../GitHub/FYS4220-project/project/src/tx_fsm.vhd
add_fileset_file rx_fsm.vhd VHDL PATH ../../GitHub/FYS4220-project/project/src/rx_fsm.vhd
add_fileset_file shift_rx.vhd VHDL PATH ../../GitHub/FYS4220-project/project/src/shift_rx.vhd
add_fileset_file shift_tx.vhd VHDL PATH ../../GitHub/FYS4220-project/project/src/shift_tx.vhd


# 
# parameters
# 
add_parameter GC_SYSTEM_CLK INTEGER 50000000
set_parameter_property GC_SYSTEM_CLK DEFAULT_VALUE 50000000
set_parameter_property GC_SYSTEM_CLK DISPLAY_NAME GC_SYSTEM_CLK
set_parameter_property GC_SYSTEM_CLK TYPE INTEGER
set_parameter_property GC_SYSTEM_CLK UNITS None
set_parameter_property GC_SYSTEM_CLK HDL_PARAMETER true
add_parameter GC_BAUD_RATE INTEGER 115200
set_parameter_property GC_BAUD_RATE DEFAULT_VALUE 115200
set_parameter_property GC_BAUD_RATE DISPLAY_NAME GC_BAUD_RATE
set_parameter_property GC_BAUD_RATE TYPE INTEGER
set_parameter_property GC_BAUD_RATE UNITS None
set_parameter_property GC_BAUD_RATE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink arst_n reset_n Input 1


# 
# connection point uart
# 
add_interface uart conduit end
set_interface_property uart associatedClock clock
set_interface_property uart associatedReset ""
set_interface_property uart ENABLED true
set_interface_property uart EXPORT_OF ""
set_interface_property uart PORT_NAME_MAP ""
set_interface_property uart CMSIS_SVD_VARIABLES ""
set_interface_property uart SVD_ADDRESS_GROUP ""

add_interface_port uart tx tx Output 1
add_interface_port uart rx rx Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset_sink
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave we write Input 1
add_interface_port avalon_slave re read Input 1
add_interface_port avalon_slave wdata writedata Input 32
add_interface_port avalon_slave rdata readdata Output 32
add_interface_port avalon_slave addr address Input 2
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

